[project]
name = "42-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LU Yanru", email = "39545418+Lu-Yanru@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.0",
    "langchain-openrouter>=0.2.8",
    "langgraph>=1.2.11",
]

[project.scripts]
42-ai-agent = "42_ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
